language: node_js
node_js: '10'

before_install:
  - yarn install

script:
  - yarn build
  - yarn test-ci
cache:
  yarn: true

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  target_branch: 'gh-pages'
  local_dir: 'dist'
  on:
    branch: master
